<?xml version="1.0" encoding="utf-8"?>
<!--
 ~ Copyright (c) 2009-2011, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~
 ~      http://www.apache.org/licenses/LICENSE-2.0
 ~
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <groupId>org.wso2.carbon.apimgt</groupId>
        <artifactId>apimgt-feature</artifactId>
        <version>9.29.160-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>org.wso2.carbon.apimgt.feature</artifactId>
    <packaging>pom</packaging>
    <name>WSO2 Carbon - Api Management Feature</name>
    <url>http://wso2.org</url>
    <description>This feature contains the bundles required for API management</description>

    <dependencies>
        <dependency>
            <groupId>org.wso2.carbon.apimgt</groupId>
            <artifactId>org.wso2.carbon.apimgt.core.feature</artifactId>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>org.wso2.carbon.apimgt</groupId>
            <artifactId>org.wso2.carbon.apimgt.keymanager.feature</artifactId>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>org.wso2.carbon.apimgt</groupId>
            <artifactId>org.wso2.carbon.apimgt.tokenmgt.feature</artifactId>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>org.wso2.carbon.apimgt</groupId>
            <artifactId>org.wso2.carbon.apimgt.jms.listener.feature</artifactId>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>org.wso2.carbon.apimgt</groupId>
            <artifactId>org.wso2.carbon.apimgt.persistence.feature</artifactId>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.upnp</artifactId>
            <version>1.2.1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.osgi/org.osgi.service.device -->
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.device</artifactId>
            <version>1.1.1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.osgi/org.osgi.service.event -->
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.event</artifactId>
            <version>1.4.1</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.osgi/org.osgi.service.wireadmin -->
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.wireadmin</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.provisioning</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.useradmin</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.metatype</artifactId>
            <version>1.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.permissionadmin</artifactId>
            <version>1.2.1</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.http.whiteboard</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.http.servlet-api</artifactId>
            <version>1.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.http.service.api</artifactId>
            <version>1.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.osgi.services</artifactId>
            <version>3.12.0</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.component</artifactId>
            <version>1.5.1</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.util.promise</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.util.function</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.cm</artifactId>
            <version>1.6.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.wso2.maven</groupId>
                <artifactId>carbon-p2-plugin</artifactId>
                <version>${carbon.p2.plugin.version}</version>
                <executions>
                    <execution>
                        <id>4-p2-feature-generation</id>
                        <phase>package</phase>
                        <goals>
                            <goal>p2-feature-gen</goal>
                        </goals>
                        <configuration>
                            <id>org.wso2.carbon.apimgt</id>
                            <propertiesFile>../../etc/feature.properties</propertiesFile>
                            <bundles>
                                <bundleDef>org.eclipse.platform:org.eclipse.osgi.services</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.component</bundleDef>
                                <bundleDef>org.osgi:org.osgi.util.function</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.cm</bundleDef>
                                <bundleDef>org.osgi:org.osgi.util.promise</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.upnp</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.device</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.event</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.wireadmin</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.provisioning</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.useradmin</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.metatype</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.permissionadmin</bundleDef>
                                <bundleDef>org.osgi:org.osgi.service.http.whiteboard</bundleDef>
                                <bundleDef>org.apache.felix:org.apache.felix.http.servlet-api</bundleDef>
                                <bundleDef>org.eclipse.platform:org.eclipse.equinox.http.service.api</bundleDef>

                            </bundles>
                            <importFeatures>
                                <importFeatureDef>org.wso2.carbon.core:compatible:${carbon.kernel.feature.version}</importFeatureDef>
                            </importFeatures>
                            <includedFeatures>
                                <includedFeatureDef>
                                    org.wso2.carbon.apimgt:org.wso2.carbon.apimgt.core.feature:${carbon.apimgt.version}
                                </includedFeatureDef>
                                <includedFeatureDef>
                                    org.wso2.carbon.apimgt:org.wso2.carbon.apimgt.keymanager.feature:${carbon.apimgt.version}
                                </includedFeatureDef>
                                <includedFeatureDef>
                                    org.wso2.carbon.apimgt:org.wso2.carbon.apimgt.tokenmgt.feature:${carbon.apimgt.version}
                                </includedFeatureDef>
                                <includedFeatureDef>
                                    org.wso2.carbon.apimgt:org.wso2.carbon.apimgt.persistence.feature:${carbon.apimgt.version}
                                </includedFeatureDef>
                            </includedFeatures>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
